// <auto-generated />
using LabCMS.FixtureDomain.Server.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LabCMS.FixtureDomain.Server.Migrations
{
    [DbContext(typeof(FixtureYearUsedIndicesRepository))]
    partial class FixtureYearUsedIndicesRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("LabCMS.FixtureDomain.Server.Models.YearUsedIndex", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("UsedIndex")
                        .HasColumnType("integer");

                    b.HasKey("Year");

                    b.ToTable("YearUsedIndices");
                });
#pragma warning restore 612, 618
        }
    }
}
